
jsGitInNode = false

$.getScript("/vendor/md5.js")
$.getScript("/lib/binary_file.js")
$.getScript("/lib/string_helpers.js")
$.getScript("/vendor/sha1.js")
$.getScript("/vendor/sha2.js")
$.getScript("/vendor/underscore-min.js")
$.getScript("/vendor/js-deflate/rawinflate.js")
$.getScript("/vendor/js-deflate/rawdeflate.js")
$.getScript("/lib/git.js")
$.getScript("/lib/git/upload_pack_parser.js")
$.getScript("/lib/git/pack.js")
$.getScript("/lib/git/memory_repo.js")
$.getScript("/lib/git/remote.js")
$.getScript("/lib/git/http_remote.js")
$.getScript("/lib/git/smart_http_remote.js")
$.getScript("/lib/git/objects.js")
$.getScript("/lib/git/file-diff.js")
$.getScript("/lib/git/tree-diff.js")
$.getScript("/lib/git/delta.js")
$.getScript("/lib/git/pack_index.js")