
jsGitInNode = false

$.getScript("/vendor/md5.js")
$.getScript("/lib/binary_file.js")
$.getScript("/lib/string_helpers.js")
$.getScript("/vendor/sha1.js")
$.getScript("/vendor/sha2.js")
$.getScript("/vendor/underscore-min.js")
$.getScript("/vendor/js-deflate/rawinflate.js")
$.getScript("/vendor/js-deflate/rawdeflate.js")
$.getScript("/lib/jsgit.js")
$.getScript("/lib/jsgit/upload_pack_parser.js")
$.getScript("/lib/jsgit/pack.js")
$.getScript("/lib/jsgit/memory_repo.js")
$.getScript("/lib/jsgit/remote.js")
$.getScript("/lib/jsgit/http_remote.js")
$.getScript("/lib/jsgit/smart_http_remote.js")
$.getScript("/lib/jsgit/objects.js")
$.getScript("/lib/jsgit/diff.js")
$.getScript("/lib/jsgit/delta.js")
$.getScript("/lib/jsgit/pack_index.js")