$.getScript("lib/binary_file.js")
$.getScript("lib/string_helpers.js")
$.getScript("vendor/sha1.js")
$.getScript("vendor/js-deflate/rawinflate.js")
$.getScript("vendor/js-deflate/rawdeflate.js")
$.getScript("lib/jsgit.js")